### ISSUE TITLE
Comparing cohorts with same people in and same index date give normal density plots

### ISSUE THREAD

**Issue by albertpratsu** [darwin-eu/CohortCharacteristics#133]
This usually happens because everyone is from -1 to 1 days (0) and the density gets calculated as a continuous distribution between -1 and 1... we may need to make everything  0, or force the graph to go from -5 to 5 or something similar. 

![image](https://github.com/darwin-eu-dev/CohortCharacteristics/assets/44193724/0dd4be54-cdaa-4f33-9528-aef3f644d231)

**Comment by catalamarti** [comment]
This is the behaviour of density function, what would you expect?
Do you want a bar plot? Just a peak at 0?

**Comment by catalamarti** [comment]
that would be a different estimate. I am happy to support 'histogram' estimate the same way we support 'density' estimate in PatientProfiles.

**Comment by catalamarti** [comment]
add a minimum width for the y axis in plotCohortTiming  at least c(-5, 5)
