### ISSUE TITLE
plotCohortCharacteristics 

### ISSUE THREAD

**Issue by nmercadeb** [darwin-eu/CohortCharacteristics#210]
When I use plotCohortCharacteristics with `uniqueCombinations = TRUE` it returns an empty plot since `getUniqueCombinationsSr(result)` returns an empty result

Also, with  `uniqueCombinations = FALSE` I get the following plot, with both green and blue at the right side instead of reference right and comparator left
![image](https://github.com/user-attachments/assets/eae017dd-7b3e-4bc0-889e-ecba4fc3c051)

**Comment by catalamarti** [comment]
hi @nmercadeb it works for me:

``` r
cdm <- omock::mockCdmFromTables(tables = list(cohort1 = dplyr::tibble(
  cohort_definition_id = c(1, 1, 2, 2),
  subject_id = c(1, 2, 2, 3),
  cohort_start_date = as.Date("2020-01-01"),
  cohort_end_date = as.Date("2020-01-01")
)))
result <- CohortCharacteristics::summariseCohortOverlap(cdm$cohort1)
CohortCharacteristics::plotCohortOverlap(result) +
  ggplot2::xlab("my custom y label")
```

![](https://i.imgur.com/VLcyW3I.png)

<sup>Created on 2024-11-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Note that x and y axis are interchanged as `ggplot2::coord_flip()` is used to make the bar plot horizontally. Is that what you wanted?

**Comment by nmercadeb** [comment]
Yes, thanks!
